In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [26]:
df = pd.read_csv("hiring.csv")

In [27]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
ndf = df.dropna()

In [6]:
ndf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
7     eleven                    7.0                           8      80000

In [7]:
word_to_int = {
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six':6,
    'seven':7,
    'ten':10,
    'eleven':11,
}


In [30]:
df['experience'] = df['experience'].apply(lambda x: word_to_int.get(x, x))

In [31]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [10]:
ndf = df.dropna()

In [11]:
ndf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
7        11.0                    7.0                           8      80000

In [12]:
firstreg = linear_model.LinearRegression()

In [14]:
firstreg.fit(ndf[['test_score(out of 10)','interview_score(out of 10)','salary($)']],ndf.experience)

LinearRegression()

In [20]:
firstreg.predict([[8,6,85000]])

C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.34003973])

In [28]:
df.experience = df.experience.fillna(0)

In [34]:
ldf= df.dropna()

In [35]:
ldf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
7          11                    7.0                           8      80000

In [32]:
secondreg = linear_model.LinearRegression()

In [36]:
secondreg.fit(ldf[['experience','interview_score(out of 10)','salary($)']],ldf['test_score(out of 10)'])

LinearRegression()

In [37]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [38]:
secondreg.predict([[10,7,72000]])

C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.38023349])

In [39]:
ldf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
7          11                    7.0                           8      80000

In [46]:
a=ldf['test_score(out of 10)'].median()

In [45]:
import math

In [47]:
a = math.floor(a)

In [48]:
a

8

In [49]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(a)

In [50]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [51]:
reg =linear_model.LinearRegression()

In [52]:
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [53]:
reg.predict([[2,9,6]])

C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [54]:
reg.predict([[12,10,10]])

C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])