In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
ir = load_iris()


In [2]:
dir(ir)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
from sklearn.model_selection import cross_val_score

In [4]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), ir.data, ir.target,cv=3)

C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


array([0.96, 0.96, 0.94])

In [6]:
cross_val_score(SVC(gamma='auto'), ir.data, ir.target,cv=3)

array([0.98, 0.98, 0.96])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=1000),ir.data, ir.target,cv=3)


array([0.98, 0.94, 0.96])

In [20]:
cross_val_score(DecisionTreeClassifier(),ir.data, ir.target,cv=3)

array([0.98, 0.94, 1.  ])