In [1]:
import matplotlib.pyplot as plt

In [2]:
import numpy as np

In [23]:
from sklearn.linear_model import LogisticRegression

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.ensemble import RandomForestClassifier

In [6]:
from sklearn.svm import SVC

In [7]:
from sklearn.datasets import load_digits

In [8]:
ld = load_digits()

In [13]:
dir(ld)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(ld.data,ld.target,test_size=0.3)

In [15]:
lr =LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [16]:
lr.score(X_test,y_test)

0.6246535634474635

In [18]:
svc = SVC()
svc.fit(X_train,y_train)

SVC()

In [19]:
svc.score(X_test,y_test)

0.9925925925925926

In [20]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [21]:
rf.score(X_test,y_test)

0.975925925925926

In [22]:
#another way:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(LogisticRegression(),ld.data,ld.target,cv=3)

C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ziad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.92153589, 0.94156928, 0.91652755])

In [25]:
cross_val_score(SVC(),ld.data,ld.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [26]:
cross_val_score(RandomForestClassifier(),ld.data,ld.target,cv=3)

array([0.93322204, 0.95993322, 0.92821369])

In [27]:
cross_val_score(LinearRegression(),ld.data,ld.target,cv=3)

array([0.52105031, 0.56814242, 0.41943985])